SOURCES = startup_stm32_cld.c libstm32f10x.a liblwip4.a syscalls.c \
          board_conf.c board_init.c board_led.c util_bkp.c \
          util_delay.c util_eth_nc.c util_led.c util_lwip.c \
          util_rtc.c util_time.c ex_tcp_clnt_bkp.c tcp_client_bkp.c

TARGETS = tcp_clnt_bkp.elf tcp_clnt_bkp.bin

all : targets

include ../scripts/makefile.in
