SOURCES = startup_stm32_cld.c libstm32f10x.a syscalls.c \
          board_lcd_ks0108.c font5x8.c util_delay.c util_lcd.c \
          ex_lcd.c

TARGETS = lcd.elf lcd.bin

all : targets

include ../scripts/makefile.in
