SOURCES = startup_stm32_cld.c libstm32f10x.a liblwip4.a syscalls.c \
          board_conf.c board_init.c board_led.c util_delay.c \
          util_eth_nc.c util_led.c util_lwip.c util_time.c \
          ex_udpd.c udp_server.c

TARGETS = udpd.elf udpd.bin

all : targets

include ../scripts/makefile.in
