SOURCES = startup_stm32_cld.c libstm32f10x.a syscalls.c \
          board_lcd_ks0108.c board_led.c board_init.c \
          font5x8.c util_delay.c util_lcd.c util_led.c ex_eth.c

TARGETS = eth.elf eth.bin

all : targets

include ../scripts/makefile.in
